# Generated by Django 2.2.6 on 2019-10-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_auto_20191021_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Modelo')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Presentacion')),
                ('tipo_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.TipoArticulo')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.UnidadMedida')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
