# Generated by Django 2.2.6 on 2019-10-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_kardex_tipomovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='tipo_movimiento',
            field=models.IntegerField(),
        ),
    ]
