# Generated by Django 2.2.6 on 2019-10-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_auto_20191021_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=250)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Comunidad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Genero')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=250)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Comunidad')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.EstadoCivil')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Genero')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
